# Generated by Django 4.2.6 on 2023-10-19 14:19

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_footer_navbar_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="footer",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footer_links",
                to="home.footer",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="nav_bar",
            field=modelcluster.fields.ParentalKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nav_links",
                to="home.navbar",
            ),
        ),
    ]
