# Generated by Django 4.2.6 on 2023-10-20 17:19

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_aboutpage_body_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='footer',
            name='text',
            field=wagtail.fields.RichTextField(help_text='Footer text.', null=True),
        ),
    ]
